package com.zhdtedu.system.dao.mapper;

import com.zhdtedu.system.dao.entity.Department;
import com.zhdtedu.system.dao.entity.DepartmentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DepartmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_department
     *
     * @mbggenerated Wed Jul 17 16:10:47 CST 2019
     */
    int countByExample(DepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_department
     *
     * @mbggenerated Wed Jul 17 16:10:47 CST 2019
     */
    int deleteByExample(DepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_department
     *
     * @mbggenerated Wed Jul 17 16:10:47 CST 2019
     */
    int insert(Department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_department
     *
     * @mbggenerated Wed Jul 17 16:10:47 CST 2019
     */
    int insertSelective(Department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_department
     *
     * @mbggenerated Wed Jul 17 16:10:47 CST 2019
     */
    List<Department> selectByExample(DepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_department
     *
     * @mbggenerated Wed Jul 17 16:10:47 CST 2019
     */
    int updateByExampleSelective(@Param("record") Department record, @Param("example") DepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_department
     *
     * @mbggenerated Wed Jul 17 16:10:47 CST 2019
     */
    int updateByExample(@Param("record") Department record, @Param("example") DepartmentExample example);
    int getTotalCount(@Param("partId")Integer partId) ;

    List<Department> selectByList(@Param("partId") Integer partId);

    int  deleteByDepartment(int id);
    //修改部门
    int  updateByPrimaryKey(@Param("record")Department record);
    //	根据 用户id查询部门
    List<Department> findDeptByUid(@Param("userId")Integer userId);
}