package com.zhdtedu.system.dao.mapper;

import com.zhdtedu.system.dao.entity.Department;
import com.zhdtedu.system.dao.entity.Privilege;
import com.zhdtedu.system.dao.entity.PrivilegeExample;
import java.util.List;

import com.zhdtedu.system.dao.entity.User;
import org.apache.ibatis.annotations.Param;

public interface PrivilegeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_privilege
     *
     * @mbg.generated Thu Jul 25 09:56:50 CST 2019
     */
    long countByExample(PrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_privilege
     *
     * @mbg.generated Thu Jul 25 09:56:50 CST 2019
     */
    int deleteByExample(PrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_privilege
     *
     * @mbg.generated Thu Jul 25 09:56:50 CST 2019
     */
    int insert(Privilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_privilege
     *
     * @mbg.generated Thu Jul 25 09:56:50 CST 2019
     */
    int insertSelective(Privilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_privilege
     *
     * @mbg.generated Thu Jul 25 09:56:50 CST 2019
     */
    List<Privilege> selectByExample(PrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_privilege
     *
     * @mbg.generated Thu Jul 25 09:56:50 CST 2019
     */
    int updateByExampleSelective(@Param("record") Privilege record, @Param("example") PrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_privilege
     *
     * @mbg.generated Thu Jul 25 09:56:50 CST 2019
     */
    int updateByExample(@Param("record") Privilege record, @Param("example") PrivilegeExample example);
    List<Privilege> selectByExample2(@Param("pageNo") Integer pageNo,
                                @Param("pageSize") Integer pageSize);
    int getTotalCount();
    int deleteByPrivilege(int privilegeId);
    int  updateByPrimaryKey(@Param("record") Privilege privilege);
    //	根据 角色id查询权限
    List<Privilege> findPrigByRid(@Param("roleId")Integer roleId);
    List<Privilege> selectByExample3(
            @Param("roleId") Integer roleId,
            @Param("pageNo") Integer pageNo,
            @Param("pageSize") Integer pageSize);
    int getTotalCountBy(@Param("roleId") Integer roleId);
    List<Privilege> selectByExample4(
            @Param("roleId") Integer roleId);
    List<Privilege> selectByList(@Param("partId") Integer partId);

}