package com.zhdtedu.system.dao.mapper;

import com.zhdtedu.system.dao.entity.UserDepartment;
import com.zhdtedu.system.dao.entity.UserDepartmentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserDepartmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_department
     *
     * @mbggenerated Wed Jul 17 16:10:47 CST 2019
     */
    int countByExample(UserDepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_department
     *
     * @mbggenerated Wed Jul 17 16:10:47 CST 2019
     */
    int deleteByExample(UserDepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_department
     *
     * @mbggenerated Wed Jul 17 16:10:47 CST 2019
     */
    int insert(UserDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_department
     *
     * @mbggenerated Wed Jul 17 16:10:47 CST 2019
     */
    int insertSelective(UserDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_department
     *
     * @mbggenerated Wed Jul 17 16:10:47 CST 2019
     */
    List<UserDepartment> selectByExample(UserDepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_department
     *
     * @mbggenerated Wed Jul 17 16:10:47 CST 2019
     */
    int updateByExampleSelective(@Param("record") UserDepartment record, @Param("example") UserDepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_department
     *
     * @mbggenerated Wed Jul 17 16:10:47 CST 2019
     */
    int updateByExample(@Param("record") UserDepartment record, @Param("example") UserDepartmentExample example);
    int deleteByUserDepartment(int userId);
}