package com.zhdtedu.system.dao.mapper;

import com.zhdtedu.system.dao.entity.*;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_users
     *
     * @mbggenerated Wed Jul 17 16:10:47 CST 2019
     */
    int countByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_users
     *
     * @mbggenerated Wed Jul 17 16:10:47 CST 2019
     */
    int deleteByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_users
     *
     * @mbggenerated Wed Jul 17 16:10:47 CST 2019
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_users
     *
     * @mbggenerated Wed Jul 17 16:10:47 CST 2019
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_users
     *
     * @mbggenerated Wed Jul 17 16:10:47 CST 2019
     */
    List<User> selectByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_users
     *
     * @mbggenerated Wed Jul 17 16:10:47 CST 2019
     */
    int updateByExampleSelective(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_users
     *
     * @mbggenerated Wed Jul 17 16:10:47 CST 2019
     */
    int updateByExample(@Param("record") User record, @Param("example") UserExample example);

    List<User> selectByExample2(@Param("deptId") int deptId,
                                @Param("pageNo") Integer pageNo,
                                @Param("pageSize") Integer pageSize);
    int getTotalCount(@Param("deptId") int deptId);
    int deleteByUser(int id);
    int  updateByPrimaryKey(@Param("record") User user);
    List<User> selectByExample3(
                                @Param("userName") String userName,
                                @Param("roleName") String roleName,
                                @Param("deptId") Integer deptId,
                                @Param("pageNo") Integer pageNo,
                                @Param("pageSize") Integer pageSize);
    int getTotalCountBy(@Param("userName") String userName,
                        @Param("roleName") String roleName,
                        @Param("deptId") Integer deptId);
    //用户登录
    User login(@Param("account")String account,@Param("password")String password);
    //	根据 用户id查询角色
    List<Role> findRoleByUid(@Param("userId")Integer userId);
    User getByAccount(@Param("account")String account);
}