#默认使用配置
spring:
  profiles:
    active: dev

#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.zhdtedu.riverchiefs.bean,com.zhdtedu.system.bean
  mapperLocations: classpath:com/zhdtedu/riverchiefs/dao/mapper/*.xml,classpath:com/zhdtedu/system/dao/mapper/*.xml
---
server:
  port: 8080
#开发配置172.2.15.201localhost
spring:
  profiles: dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://172.2.15.201:3306/rcsdb?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    #url: jdbc:mysql://localhost:3306/rcsdb?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    #username: root
    #password: root
    username: zhdt
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

    #redis
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    #    host: 127.0.0.1localhost
    host: localhost
    # Redis服务器连接端口
    port: 3306
    # Redis服务器连接密码（默认为空）
    password:
    # 连接超时时间（毫秒）
    timeout: 0
    # 连接池最大连接数（使用负值表示没有限制）
    # 默认生命周期30天
    defaultExpiration: 2592000
    # 服务器上下文路径
    contextPath: contextPath
    jedis:
      pool:
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
  http:
    encoding:
      charset: utf-8
      enabled: true

    #配置JSP视图
    mvc:
      view:
        prefix: /WEB-INF/jsp/
        suffix: .jsp
      #控制台打印sql语句
        logging:
          level:
            com.ming.ssm.mapper: debug
